### ISSUE TITLE
Model checkpoints

### ISSUE THREAD

**Issue by tttonyalpha** [CXH-Research/FilmNet#2]
Do you have any model checkpoints?

**Comment by xuhangc** [comment]
I apologize, but we are unable to provide the model weights because this paper's model and dataset directly benchmark Fujifilm's film simulations. Releasing the model weights could potentially lead to commercial applications infringing on Fujifilm's patents and copyrights. If you are interested, you can train the model yourself to obtain the weights.

**Comment by xuhangc** [comment]
> Do you have any model checkpoints?

@tttonyalpha Hi! We've released the checkpoints for MIT-Adobe 5K and HDR+ for your convenience. You can find them here: https://github.com/CXH-Research/FilmNet/releases/tag/weights.
